/* Generated By:JavaCC: Do not edit this line. CompiladorExemploConstants.java */
package Principal;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorExemploConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 5;
  /** RegularExpression Id. */
  int IDENT = 6;
  /** RegularExpression Id. */
  int ATRIB = 7;
  /** RegularExpression Id. */
  int ADICAO = 8;
  /** RegularExpression Id. */
  int PT_VIRG = 9;
  /** RegularExpression Id. */
  int UM = 10;
  /** RegularExpression Id. */
  int DOIS = 11;
  /** RegularExpression Id. */
  int TRES = 12;
  /** RegularExpression Id. */
  int QUATRO = 13;
  /** RegularExpression Id. */
  int CINCO = 14;
  /** RegularExpression Id. */
  int SEIS = 15;
  /** RegularExpression Id. */
  int SETE = 16;
  /** RegularExpression Id. */
  int OITO = 17;
  /** RegularExpression Id. */
  int NOVE = 18;
  /** RegularExpression Id. */
  int DEZ = 19;
  /** RegularExpression Id. */
  int VINTE = 20;
  /** RegularExpression Id. */
  int TRINTA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"exibe\"",
    "<IDENT>",
    "\":=\"",
    "\"+\"",
    "\";\"",
    "\"I\"",
    "\"II\"",
    "\"III\"",
    "\"IV\"",
    "\"V\"",
    "\"VI\"",
    "\"VII\"",
    "\"VIII\"",
    "\"IX\"",
    "\"X\"",
    "\"XX\"",
    "\"XXX\"",
  };

}
